apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "wUjgN6YeBqqwg4XYSRRgTo/+jNmq81AOa48IFW1KS3ewlRt4kVW4HxzjtFd+e4of\nDHwpvS1CjDeZ8u0p3VN1m2C7Jsza5eixR8FVTekM+g34EcWlWwZek3XqKjXxdIXJ\nsvH5Ro06Tllw2vc+sBcJDGPr+Xh/FvjqfIqpJRP46OE="
